stages:
  pull:
    cmd: python Scripte/getData.py
    outs: 
      - FeatureDataTest.npy
  train:
    cmd: python Scripte/ModelTesting.py
    deps:
    - Scripte/ModelTesting.py
    
    outs:
    - MetricsMLBarplot.png
    - MetricsMLConfusionmatrix.png    
    metrics:
    - metrics.json:
        cache: false
