name: testml
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
        
          dvc metrics show
          dvc metrics diff --targets metrics.json --show-md  > report.md
          
          # Add figure to the report
          echo "## Validating results by region"
          cml-publish Abbildungen/MetricsMLBarplot.png --md > report.md
          cml-send-comment report.md
