name: testml
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
        
          /usr/bin/python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          
          wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1wuQbk0kPtH4sLj2X6OtYlkviNLYY_rQS' -O FeatureDataTest.npy
          wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1XYgyZAn5WqxXpkOP1v3tewzG8N5uFHOY' -O LabelTest.npy
          dvc pull FeatureDataTest.npy
          dvc pull LabelTest.npy
          
          dvc repro 
          git fetch --prune
          dvc metrics diff --show-md master > report.md
          
          # Add figure to the report
          echo "## Validating results by region"
          cml-publish MetricsMLBarplot.png --md >> report.md
          cml-send-comment report.md
